# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_cuadrupedo/motors_states.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class motors_states(genpy.Message):
  _md5sum = "889997f071d49233501da79c98b3e3ac"
  _type = "robot_cuadrupedo/motors_states"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 frontal_motor
float64 posterior_motor
bool walk
bool goal_position_feedback
int64 id_f
int64 id_p"""
  __slots__ = ['frontal_motor','posterior_motor','walk','goal_position_feedback','id_f','id_p']
  _slot_types = ['float64','float64','bool','bool','int64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       frontal_motor,posterior_motor,walk,goal_position_feedback,id_f,id_p

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(motors_states, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.frontal_motor is None:
        self.frontal_motor = 0.
      if self.posterior_motor is None:
        self.posterior_motor = 0.
      if self.walk is None:
        self.walk = False
      if self.goal_position_feedback is None:
        self.goal_position_feedback = False
      if self.id_f is None:
        self.id_f = 0
      if self.id_p is None:
        self.id_p = 0
    else:
      self.frontal_motor = 0.
      self.posterior_motor = 0.
      self.walk = False
      self.goal_position_feedback = False
      self.id_f = 0
      self.id_p = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2d2B2q().pack(_x.frontal_motor, _x.posterior_motor, _x.walk, _x.goal_position_feedback, _x.id_f, _x.id_p))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 34
      (_x.frontal_motor, _x.posterior_motor, _x.walk, _x.goal_position_feedback, _x.id_f, _x.id_p,) = _get_struct_2d2B2q().unpack(str[start:end])
      self.walk = bool(self.walk)
      self.goal_position_feedback = bool(self.goal_position_feedback)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2d2B2q().pack(_x.frontal_motor, _x.posterior_motor, _x.walk, _x.goal_position_feedback, _x.id_f, _x.id_p))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 34
      (_x.frontal_motor, _x.posterior_motor, _x.walk, _x.goal_position_feedback, _x.id_f, _x.id_p,) = _get_struct_2d2B2q().unpack(str[start:end])
      self.walk = bool(self.walk)
      self.goal_position_feedback = bool(self.goal_position_feedback)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d2B2q = None
def _get_struct_2d2B2q():
    global _struct_2d2B2q
    if _struct_2d2B2q is None:
        _struct_2d2B2q = struct.Struct("<2d2B2q")
    return _struct_2d2B2q
