// Generated by gencpp from file quadruped_robot/period.msg
// DO NOT EDIT!


#ifndef QUADRUPED_ROBOT_MESSAGE_PERIOD_H
#define QUADRUPED_ROBOT_MESSAGE_PERIOD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace quadruped_robot
{
template <class ContainerAllocator>
struct period_
{
  typedef period_<ContainerAllocator> Type;

  period_()
    : T(0.0)  {
    }
  period_(const ContainerAllocator& _alloc)
    : T(0.0)  {
  (void)_alloc;
    }



   typedef double _T_type;
  _T_type T;





  typedef boost::shared_ptr< ::quadruped_robot::period_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadruped_robot::period_<ContainerAllocator> const> ConstPtr;

}; // struct period_

typedef ::quadruped_robot::period_<std::allocator<void> > period;

typedef boost::shared_ptr< ::quadruped_robot::period > periodPtr;
typedef boost::shared_ptr< ::quadruped_robot::period const> periodConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadruped_robot::period_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadruped_robot::period_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadruped_robot::period_<ContainerAllocator1> & lhs, const ::quadruped_robot::period_<ContainerAllocator2> & rhs)
{
  return lhs.T == rhs.T;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadruped_robot::period_<ContainerAllocator1> & lhs, const ::quadruped_robot::period_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadruped_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadruped_robot::period_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadruped_robot::period_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadruped_robot::period_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadruped_robot::period_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadruped_robot::period_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadruped_robot::period_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadruped_robot::period_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df792c00269de90b579eb8eab6fc9c54";
  }

  static const char* value(const ::quadruped_robot::period_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf792c00269de90bULL;
  static const uint64_t static_value2 = 0x579eb8eab6fc9c54ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadruped_robot::period_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadruped_robot/period";
  }

  static const char* value(const ::quadruped_robot::period_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadruped_robot::period_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 T\n"
;
  }

  static const char* value(const ::quadruped_robot::period_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadruped_robot::period_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.T);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct period_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadruped_robot::period_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadruped_robot::period_<ContainerAllocator>& v)
  {
    s << indent << "T: ";
    Printer<double>::stream(s, indent + "  ", v.T);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADRUPED_ROBOT_MESSAGE_PERIOD_H
