// Generated by gencpp from file quadruped_robot/read_dxl.msg
// DO NOT EDIT!


#ifndef QUADRUPED_ROBOT_MESSAGE_READ_DXL_H
#define QUADRUPED_ROBOT_MESSAGE_READ_DXL_H

#include <ros/service_traits.h>


#include <quadruped_robot/read_dxlRequest.h>
#include <quadruped_robot/read_dxlResponse.h>


namespace quadruped_robot
{

struct read_dxl
{

typedef read_dxlRequest Request;
typedef read_dxlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct read_dxl
} // namespace quadruped_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::quadruped_robot::read_dxl > {
  static const char* value()
  {
    return "044408118166cb6346b6bae601023969";
  }

  static const char* value(const ::quadruped_robot::read_dxl&) { return value(); }
};

template<>
struct DataType< ::quadruped_robot::read_dxl > {
  static const char* value()
  {
    return "quadruped_robot/read_dxl";
  }

  static const char* value(const ::quadruped_robot::read_dxl&) { return value(); }
};


// service_traits::MD5Sum< ::quadruped_robot::read_dxlRequest> should match
// service_traits::MD5Sum< ::quadruped_robot::read_dxl >
template<>
struct MD5Sum< ::quadruped_robot::read_dxlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::quadruped_robot::read_dxl >::value();
  }
  static const char* value(const ::quadruped_robot::read_dxlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::quadruped_robot::read_dxlRequest> should match
// service_traits::DataType< ::quadruped_robot::read_dxl >
template<>
struct DataType< ::quadruped_robot::read_dxlRequest>
{
  static const char* value()
  {
    return DataType< ::quadruped_robot::read_dxl >::value();
  }
  static const char* value(const ::quadruped_robot::read_dxlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::quadruped_robot::read_dxlResponse> should match
// service_traits::MD5Sum< ::quadruped_robot::read_dxl >
template<>
struct MD5Sum< ::quadruped_robot::read_dxlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::quadruped_robot::read_dxl >::value();
  }
  static const char* value(const ::quadruped_robot::read_dxlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::quadruped_robot::read_dxlResponse> should match
// service_traits::DataType< ::quadruped_robot::read_dxl >
template<>
struct DataType< ::quadruped_robot::read_dxlResponse>
{
  static const char* value()
  {
    return DataType< ::quadruped_robot::read_dxl >::value();
  }
  static const char* value(const ::quadruped_robot::read_dxlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QUADRUPED_ROBOT_MESSAGE_READ_DXL_H
